services:
  simple-apps:
    container_name: ct-simpleapps-prod
    image: alfanizidni/img-simpleapps
    build: ./app
    ports:
      - "10000:3000"      
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M